# Generated by Django 4.1.3 on 2022-12-06 03:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="date_updated",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
