# Generated by Django 4.1.4 on 2022-12-25 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0004_alter_review_content"),
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="review",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="review.review",
                verbose_name="評論",
            ),
        ),
    ]
