# Generated by Django 4.1.3 on 2022-12-03 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="rating",
            field=models.CharField(default="5", max_length=10),
        ),
    ]
