# Generated by Django 4.1.3 on 2022-12-04 03:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("review", "0002_review_rating"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="user_id",
        ),
        migrations.AddField(
            model_name="review",
            name="user_id",
            field=models.ManyToManyField(
                through="review.heart", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
