# Generated by Django 4.1.3 on 2022-12-04 04:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("review", "0003_remove_review_user_id_review_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="user_id",
            field=models.ManyToManyField(
                through="review.Heart", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
