# Generated by Django 4.1.4 on 2022-12-25 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0003_alter_review_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="content",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
