# Generated by Django 4.1.3 on 2022-12-01 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("content", models.TextField()),
                ("official_site", models.TextField()),
                ("time", models.TextField()),
                ("grade", models.TextField()),
                ("date_released", models.DateTimeField()),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "Movie",
            },
        ),
    ]
