# Generated by Django 4.1.3 on 2022-12-13 06:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="搞笑", max_length=10)),
                ("description", models.TextField(default="a")),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("content", models.TextField(max_length=500)),
                ("official_site", models.TextField()),
                ("time", models.IntegerField()),
                ("image", models.ImageField(upload_to="movies/")),
                (
                    "grade",
                    models.TextField(
                        choices=[
                            ("普遍級", "普遍級"),
                            ("保護級", "保護級"),
                            ("輔12級", "輔12級"),
                            ("輔15級", "輔15級"),
                            ("限制級", "限制級"),
                        ],
                        default=1,
                    ),
                ),
                ("date_released", models.DateField(default=datetime.date.today)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "tag_id",
                    models.ForeignKey(
                        default="1",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="movie.tag",
                    ),
                ),
            ],
        ),
    ]
