# Generated by Django 4.1.3 on 2022-12-14 15:42

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movie", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="content",
            field=models.TextField(max_length=500, verbose_name="content"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="date_released",
            field=models.DateField(default=datetime.date.today, verbose_name="上映日"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="grade",
            field=models.TextField(
                choices=[
                    ("普遍級", "普遍級"),
                    ("保護級", "保護級"),
                    ("輔12級", "輔12級"),
                    ("輔15級", "輔15級"),
                    ("限制級", "限制級"),
                ],
                verbose_name="分級",
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="image",
            field=models.ImageField(upload_to="movies/", verbose_name="image"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="name",
            field=models.CharField(max_length=20, verbose_name="使用者名稱"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="official_site",
            field=models.TextField(verbose_name="官方網站"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="tag_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="movie.tag"
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="time",
            field=models.IntegerField(verbose_name="時長"),
        ),
        migrations.AlterField(
            model_name="tag",
            name="description",
            field=models.TextField(verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=10, verbose_name="使用者名稱"),
        ),
    ]
