# Generated by Django 4.1.4 on 2022-12-08 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movie",
            old_name="tag_id",
            new_name="tag",
        ),
    ]
