# Generated by Django 4.1.3 on 2022-12-01 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0002_tag_alter_movie_content_alter_movie_table"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="content",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="date_created",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="date_released",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="date_updated",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="grade",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="official_site",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="time",
        ),
        migrations.AlterField(
            model_name="movie",
            name="name",
            field=models.TextField(default="a"),
        ),
        migrations.AlterModelTable(
            name="movie",
            table=None,
        ),
    ]
