# Generated by Django 4.1.3 on 2022-12-14 15:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movie", "0002_alter_movie_content_alter_movie_date_released_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="official_site",
            field=models.URLField(verbose_name="官方網站"),
        ),
    ]
