# Generated by Django 4.1.4 on 2022-12-08 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0002_rename_tag_id_movie_tag"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movie",
            old_name="tag",
            new_name="tag_id",
        ),
    ]
