# Generated by Django 4.1.3 on 2022-12-01 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0003_remove_movie_content_remove_movie_date_created_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="content",
            field=models.TextField(default="a", max_length=500),
        ),
        migrations.AddField(
            model_name="movie",
            name="date_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="grade",
            field=models.TextField(default="a"),
        ),
        migrations.AddField(
            model_name="movie",
            name="official_site",
            field=models.TextField(default="a"),
        ),
        migrations.AddField(
            model_name="movie",
            name="time",
            field=models.TextField(default="a"),
        ),
    ]
