# Generated by Django 4.1.3 on 2022-12-14 15:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movie", "0003_alter_movie_official_site"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="name",
            field=models.CharField(max_length=20, verbose_name="名稱"),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=10, verbose_name="名稱"),
        ),
    ]
