# Generated by Django 4.1.3 on 2022-12-01 15:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0004_movie_content_movie_date_updated_movie_grade_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
