# Generated by Django 4.1.3 on 2022-12-14 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movie", "0004_alter_movie_name_alter_tag_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="tag_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="movie.tag",
                verbose_name="tag",
            ),
        ),
    ]
