# Generated by Django 4.0 on 2022-12-15 06:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('movie', '0005_alter_movie_tag_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='time',
            field=models.PositiveSmallIntegerField(verbose_name='時長'),
        ),
    ]
