# Generated by Django 4.1.3 on 2022-12-01 15:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0005_movie_date_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="date_released",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
