# Generated by Django 4.1.3 on 2022-12-01 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0006_movie_date_released"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="date_released",
            field=models.DateField(default="2020-10-10"),
        ),
    ]
