# Generated by Django 4.0 on 2022-12-15 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('movie', '0006_alter_movie_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='content',
            field=models.TextField(max_length=500, verbose_name='簡介'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(upload_to='movies/', verbose_name='圖片'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='tag_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.tag', verbose_name='種類'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=models.TextField(verbose_name='敘述'),
        ),
    ]
