# Generated by Django 4.1.3 on 2022-12-01 15:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0007_alter_movie_date_released"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="tag_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="movie.tag",
            ),
            preserve_default=False,
        ),
    ]
