# Generated by Django 4.1.3 on 2022-12-01 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0008_movie_tag_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="tag_id",
        ),
    ]
