# Generated by Django 4.1.3 on 2022-12-01 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0009_remove_movie_tag_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="date_created",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="date_updated",
        ),
    ]
