# Generated by Django 4.1.3 on 2022-12-01 16:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0010_remove_movie_date_created_remove_movie_date_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="movie",
            name="date_updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
