# Generated by Django 4.1.3 on 2022-12-02 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0011_movie_date_created_movie_date_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="tag_id",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="movie.tag"
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="grade",
            field=models.TextField(default="普遍級"),
        ),
    ]
