# Generated by Django 4.1.3 on 2022-12-02 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0012_movie_tag_id_alter_movie_grade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="name",
            field=models.CharField(default="a", max_length=20),
        ),
        migrations.AlterField(
            model_name="movie",
            name="tag_id",
            field=models.ForeignKey(
                default="1", on_delete=django.db.models.deletion.CASCADE, to="movie.tag"
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=10),
        ),
    ]
