# Generated by Django 4.1.3 on 2022-12-02 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0013_alter_movie_name_alter_movie_tag_id_alter_tag_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="description",
            field=models.TextField(default="a"),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(default="搞笑", max_length=10),
        ),
    ]
